### ISSUE TITLE
Add a new crate for the AuthorizationEnclave

### ISSUE THREAD

**Issue by longtomjr** [registreerocks/rtc-data#33]
- [x] Setup compile environment to mimic the rtc_data_enclave setup. Include: 
   - `Enclave.edl`
   - `Enclave.lds`
   - `Enclave_private.pem`
   - `Enclave.config.xml`
   - `rust-toolchain`
   - `x86_64-unknown-linux-sgx.json`
 - [x] Add a build script with cbindgen to generate the bindings (see `rtc_data_enclave/build.rs`)
 - [x] Add Makefile based on the Makefile in `rtc_data_enclave`
 - [x] Add the following attributes to the lib.rs
   - `#![no_std]` -> Sets no_std (so rust does not add std prelude to the top of every file)
   - `#![feature(unsafe_block_in_unsafe_fn)]` -> Require unsafe blocks for unsafe code, even if the function is marked as unsafe
     - see [Rust RFC 2585](https://rust-lang.github.io/rfcs/2585-unsafe-block-in-unsafe-fn.html)
   - `#![deny(unsafe_op_in_unsafe_fn)]` -> Sets the lint enabled by the above feature to error if the conditions are not met
   - `#![deny(clippy::mem_forget)]` -> Disallows (via clippy) the use of mem_forget. (This should not come up at all, but it is good to prevent obvious memory leaks)

**Comment by PiDelport** [comment]
For the crate name, `rtc_auth_enclave`?

**Comment by PiDelport** [comment]
Should we copy the Makefile, or try to factor out a common base Makefile again?
